# Generated by Django 6.1 on 2026-09-01 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_ticket_unique_seat'),
        ('payments', '0003_alter_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xử lý')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền hoàn')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do hoàn tiền')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã hoàn tiền'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('admin_note', models.TextField(blank=True, verbose_name='Ghi chú của admin')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Yêu cầu hoàn tiền',
                'verbose_name_plural': 'Yêu cầu hoàn tiền',
                'ordering': ['-requested_at'],
            },
        ),
    ]
