# Generated by Django 6.1 on 2026-09-01 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_options_alter_passenger_options_and_more'),
        ('payments', '0004_refundrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Refund Request', 'verbose_name_plural': 'Refund Requests'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('banking', 'Banking'), ('mock', 'Mock Payment')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Admin Note'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='bookings.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processed At'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Refund Reason'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Refund Amount'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Requested At'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
