# Generated by Django 6.1 on 2026-10-01 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_add_stops_baggage_seats'),
        ('users', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='managed_airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='flights.airline', verbose_name='Hãng hàng không quản lý (Dành cho Đối tác)'),
        ),
    ]
