# Generated by Django 6.1 on 2026-09-01 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_aircraft_id_alter_airline_id_alter_airport_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'verbose_name': 'Aircraft', 'verbose_name_plural': 'Aircrafts'},
        ),
        migrations.AlterModelOptions(
            name='airline',
            options={'verbose_name': 'Airline', 'verbose_name_plural': 'Airlines'},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'Airport', 'verbose_name_plural': 'Airports'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Aircraft Model'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='registration_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_seats',
            field=models.PositiveIntegerField(verbose_name='Total Seats'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Airline Code'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='logo',
            field=models.URLField(blank=True, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Airline Name'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Airport Code'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Airport Name'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.aircraft', verbose_name='Aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.airline', verbose_name='Airline'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport', verbose_name='Arrival Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport', verbose_name='Departure Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(db_index=True, verbose_name='Departure Time'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=20, verbose_name='Flight Number'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20, verbose_name='Status'),
        ),
    ]
