# Generated by Django 6.1 on 2026-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_aircraft_options_alter_airline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available_seats',
            field=models.PositiveIntegerField(default=100, verbose_name='Số ghế còn lại'),
        ),
        migrations.AddField(
            model_name='flight',
            name='has_checked_baggage',
            field=models.BooleanField(default=False, help_text='Giá đã bao gồm hành lý ký gửi', verbose_name='Có hành lý ký gửi'),
        ),
        migrations.AddField(
            model_name='flight',
            name='stops',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = Bay thẳng, 1 = 1 điểm dừng, 2+ = Nhiều điểm dừng', verbose_name='Số điểm dừng'),
        ),
    ]
