import dj_database_url
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.
Environment variables are loaded from .env via python-decouple.
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── Security ──────────────────────────────────────────────────────────────────
# Read from .env — NEVER hard-code in source code
SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']


# ── Application definition ───────────────────────────────────────────────────

INSTALLED_APPS = [
    "users",
    "flights",
    "bookings",
    "payments",
    "recommendations",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ── Database ─────────────────────────────────────────────────────────────────
# SQLite: dữ liệu lưu vĩnh viễn trong file db.sqlite3 trên đĩa.
# WAL mode bảo vệ dữ liệu khỏi mất mát khi tắt máy đột ngột.
DB_PATH = str(BASE_DIR / 'db.sqlite3')

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + DB_PATH,
        conn_max_age=600
    )
}

# Kích hoạt bảo vệ dữ liệu cho SQLite
DATABASES['default'].setdefault('OPTIONS', {})
DATABASES['default']['OPTIONS']['init_command'] = (
    "PRAGMA journal_mode=WAL; "     # Ghi log trước -> chống mất dữ liệu khi tắt đột ngột
    "PRAGMA synchronous=FULL; "     # Đảm bảo flush xuống đĩa trước khi commit
    "PRAGMA foreign_keys=ON; "      # Bật ràng buộc khóa ngoại
    "PRAGMA temp_store=MEMORY; "    # Bảng tạm trong RAM -> nhanh hơn
    "PRAGMA cache_size=-32000;"     # Cache 32MB
)

# Auto-increment primary key type (removes W042 warnings)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ── Password validation ───────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ── Internationalization ──────────────────────────────────────────────────────
LANGUAGE_CODE = 'vi'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_TZ = True


# ── Static files ──────────────────────────────────────────────────────────────
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# ── Email ─────────────────────────────────────────────────────────────────────
# In development uses console backend (prints to terminal).
# Override EMAIL_BACKEND in .env for production SMTP.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@flightbooking.com')


# ── Kích hoạt bảo vệ dữ liệu SQLite qua signal ──────────────────────────────
# Django's connection_created signal chạy ngay sau khi mỗi kết nối DB được tạo.
# Đây là cách duy nhất đáng tin cậy để set PRAGMA cho SQLite với dj_database_url.
from django.db.backends.signals import connection_created

def _set_sqlite_pragmas(sender, connection, **kwargs):
    if connection.vendor == 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute("PRAGMA journal_mode=WAL;")      # Chống mất dữ liệu khi crash
            cursor.execute("PRAGMA synchronous=FULL;")      # Flush xuống đĩa trước commit
            cursor.execute("PRAGMA foreign_keys=ON;")       # Bật ràng buộc khóa ngoại
            cursor.execute("PRAGMA temp_store=MEMORY;")     # Bảng tạm trong RAM
            cursor.execute("PRAGMA cache_size=-32000;")     # Cache 32MB

connection_created.connect(_set_sqlite_pragmas)



# Auth redirects
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/'
