# Generated by Django 6.1 on 2026-09-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_flight_alter_booking_id_alter_passenger_id_and_more'),
        ('flights', '0003_alter_aircraft_id_alter_airline_id_alter_airport_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'seat_number')},
        ),
    ]
