# Generated by Django 6.1 on 2026-09-01 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_ticket_unique_seat'),
        ('flights', '0004_alter_aircraft_options_alter_airline_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Passenger', 'verbose_name_plural': 'Passengers'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='booking',
            name='return_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bookings', to='flights.flight', verbose_name='Return Flight'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passenger_type',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant')], default='adult', max_length=10, verbose_name='Passenger Type'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20, verbose_name='Seat Class'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Booking Code'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_bookings', to='flights.flight', verbose_name='Outbound Flight'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Passport Number'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight', verbose_name='Flight'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.passenger', verbose_name='Passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(max_length=10, verbose_name='Seat Number'),
        ),
    ]
