# Generated by Django 6.1 on 2026-09-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='City/Destination Name')),
                ('country', models.CharField(default='Vietnam', max_length=100, verbose_name='Country')),
                ('airport_code', models.CharField(blank=True, max_length=10, verbose_name='Airport Code')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Starting Price')),
                ('badge', models.CharField(blank=True, choices=[('hot', 'Hot'), ('new', 'New'), ('deal', 'Deal')], max_length=20, null=True, verbose_name='Badge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
    ]
